all:
	$(MAKE) -C cmisearch
	$(MAKE) -C dyad_local
	$(MAKE) -C mlisearch
	$(MAKE) -C orphans

clean:
	$(MAKE) -C cmisearch clean
	$(MAKE) -C dyad_local clean
	$(MAKE) -C mlisearch clean
	$(MAKE) -C orphans clean
