all:
	$(MAKE) -C deps_sig
	$(MAKE) -C deps_struct
	$(MAKE) -C fixedsig
	$(MAKE) -C fixedstruct
	$(MAKE) -C ns
	$(MAKE) -C orphans
	$(MAKE) -C selection
	$(MAKE) -C structs

clean:
	$(MAKE) -C deps_sig clean
	$(MAKE) -C deps_struct clean
	$(MAKE) -C fixedsig clean
	$(MAKE) -C fixedstruct clean
	$(MAKE) -C ns clean
	$(MAKE) -C orphans clean
	$(MAKE) -C selection clean
	$(MAKE) -C structs clean
