all:
	$(MAKE) -C include1
	$(MAKE) -C include2
	$(MAKE) -C opaque1
	$(MAKE) -C opaque2
	$(MAKE) -C ref1
	$(MAKE) -C ref2

clean:
	$(MAKE) -C include1 clean
	$(MAKE) -C include2 clean
	$(MAKE) -C opaque1 clean
	$(MAKE) -C opaque2 clean
	$(MAKE) -C ref1 clean
	$(MAKE) -C ref2 clean


