= rules_ocaml demos

WARNING: Some of these demos use Janestreet packages. Janestreet
evidently does not keep their github repos in sync with their master
copies. Things may break. Example: ppx_inline_test, which is at
v0.16.0 in the official opam-repository, but which has only two old
releases on its github page. Naturally, things broke somewhere along
the way, without documentation (the API for ppx_inline_test_lib
changed). Sigh.

== Getting started

Clone this repo to your local disk, then `$ cd demos_obazl/rules_ocaml`.

Your opam switch must be in good order. `.config_opam.sh` lists the
minimal opam packages needed by the demos but may not be complete; see
also the list of `bazel_dep` directives in `MODULE.bazel`. If you get
an error just install the missing package.

To bazelize your current switch: `$ bazel run @coswitch//new`.  "Current switch" can mean either shared (typically in `$HOME/.opam`) or local (in `$PWD/_opam`).

See link:https://github.com/obazl/coswitch[coswitch] for details.


WARNING: There's a bootstrapping issue. The `bazel_deps` in
`MODULE.bazel` cannot be resolved until you run `@coswitch//new`, but
to run that, they must be resolved. So you'll have to comment out all
the `bazel_dep` stuff starting with the `ocaml` one before you run
`@coswitch//new`. Once the coswitch is install, uncomment them.
Thereafter you should not need to repeat that, unless you delete
something in your switch.

Then you need to tell bazel about the registry created by
`@coswitch//new`; that's what `.config/coswitch_registry.bazelrc`
is for.  It should contain something like

    common --registry=file:///home/<uid>/.opam/5.1.1/share/obazl     # linux
    common --registry=file:///Users/<uid>/.opam/5.1.1/share/obazl    # macos

For details see link:https://github.com/obazl/coswitch[coswitch].

WARNING: This repo uses shell script `tools/bazel` to automatically
select the coswitch for the current OPAM switch. Bazel auto-detects
that file; to control coswitch selection using
`.config/coswitch_registry.bazel` just rename `tools/bazel`.

Once you've run coswitch, run

    $ bazel test test

By default the builds use the `ocamlopt.opt` toolchain. You can explicitly select a toolchain but running one of:

    $ bazel test test --config=ocamlopt.opt
    $ bazel test test --config=ocamlopt.byte
    $ bazel test test --config=ocamlc.byte
    $ bazel test test --config=ocamlc.opt

NOTE: Three demos involving `ppx_inline_test` will fail with `ocamlc` toolchains. These will be fixed eventually; if this is a problem for you now, please file an issue.
