= rules_ocaml demos

WARNING: Some of these demos use Janestreet packages. Janestreet
evidently does not keep their github repos in sync with their master
copies. Things may break. Example: ppx_inline_test, which is at
v0.16.0 in the official opam-repository, but which has only two old
releases on its github page. Naturally, things broke somewhere along
the way, without documentation (the API for ppx_inline_test_lib
changed). Sigh.

== Getting started

Clone this repo to your local disk, then `$ cd demos_obazl/rules_ocaml`.

    $ bazel test test

By default the builds use the `ocamlopt.opt` toolchain. You can explicitly select a toolchain but running one of:

    $ bazel test test --config=ocamlopt.opt
    $ bazel test test --config=ocamlopt.byte
    $ bazel test test --config=ocamlc.byte
    $ bazel test test --config=ocamlc.opt

WARNING: A small number of tests may fail with `+ocamlc.byte+` and `+ocamlc.opt+`; there's an open issue for them. Pass `--keep_going` to tell Bazel not to stop at the first error.
