= rules_ocaml demos

WARNING: Unstable. I'm in the middle of updating stuff. Some things may not work.

WARNING: Some of these demos use Janestreet packages. Janestreet
evidently does not keep their github repos in sync with their master
copies. Things may break. Example: ppx_inline_test, which is at
v0.16.0 in the official opam-repository, but which has only two old
releases on its github page. Naturally, things broke somewhere along
the way, without documentation (the API for ppx_inline_test_lib
changed). Sigh.

== Getting started

WARNING: these are temporary instructions. I'm working on aligning the demos with the latest versions of the tools, and will provide better guidance when finished.

Your opam switch must be in good order. `.config_opam.sh` lists the
minimal opam packages needed by the demos but may not be complete; see
also the list of `bazel_dep` directives in `MODULE.bazel`. If you get
an error just install the missing package.

To bazelize your current switch: `$ bazel run @coswitch//new`.  "Current switch" can mean either shared (typically in `$HOME/.opam`) or local (in `$PWD/_opam`).

WARNING: This may not work; I'm also in the middle of preparing a new
version of @coswitch with Bazel module support and OPAM integration.

This will create stuff in $XDG_DATA_HOME/share/obazl (default:
`$HOME/.local/share/obazl`).

WARNING: There's a bootstrapping issue. The `bazel_deps` in
`MODULE.bazel` cannot be resolved until you run `@coswitch//new`, but
to run that, they must be resolved. So you'll have to comment out all
the `bazel_dep` stuff starting with the `ocaml` one before you run
`@coswitch//new`. Once the coswitch is install, uncomment them.
Thereafter you should not need to repeat that, unless you delete
something in your switch.

Then you need to tell bazel about the registry created by
`@coswitch//new`; that's what `.config/coswitch_registry.bazelrc`
is for.

NOTE: I'm leaving these files under version control so the intrepid
can follow along. Ordinarly they would not be under VC.

