= rules_ocaml demos

WARNING: Some of these demos use Janestreet packages. Janestreet
evidently does not keep their github repos in sync with their master
copies. Things may break. Example: ppx_inline_test, which is at
v0.16.0 in the official opam-repository, but which has only two old
releases on its github page. Naturally, things broke somewhere along
the way, without documentation (the API for ppx_inline_test_lib
changed). Sigh.

== Getting started


=== Using a local switch

First  `cd rules_ocaml`, then:

0. `$ opam update`

1. `$ opam switch import .obazl.d/opam/local.manifest --switch .`

2. `$ bazel run @opam//coswitch/local:refresh`

3. `$ bazel test test`

WARNING: Steps 1 & 2 may take a whle. OPAM will download and compile the
entire OCaml toolsuite, then use it to compile all the packages listed
in `.obazl.d/opam/local.manifest`.

If you get errors involving missing "@something..." it probably means
your local switch/coswitch is misconfigured. Try rerunning

`$ bazel run @opam//local:refresh`.


== OPAM deps

* findlib
* ounit2
* ppxlib
* lwt (only for mwe/hello_lwt)

