default:
	$(MAKE) -C fs_alias;
	$(MAKE) -C embedded_alias;
	$(MAKE) -C embedded_defmod;
	$(MAKE) -C unresolved;

clean:
	$(MAKE) -C fs_alias clean;
	$(MAKE) -C embedded_alias clean;
	$(MAKE) -C embedded_defmod clean;
	$(MAKE) -C unresolved clean;
