COMPILER=ocamlopt
LINKALL=

default:
	$(MAKE) -C control;
	$(MAKE) -C functions;
	$(MAKE) -C letforms;
	$(MAKE) -C variants;

################################################################
clean:
	@$(MAKE) -C control clean;
	@$(MAKE) -C functions clean;
	@$(MAKE) -C letforms clean;
	@$(MAKE) -C variants clean;
