(* In this demo, the submodule implementation files are generated by
   the Makefile by copying the source files. *)
module Red   = Demos_namespaces_recursive_makefile__red
module Green = Demos_namespaces_recursive_makefile__green
module Blue  = Demos_namespaces_recursive_makefile__blue
