COMPILER=ocamlopt
LINKALL=

default:
	$(MAKE) -C args;
	$(MAKE) -C bindings;
	$(MAKE) -C sideeffects;

################################################################
clean:
	@$(MAKE) -C args clean;
	@$(MAKE) -C bindings clean;
	@$(MAKE) -C sideeffects clean;
