=  ppx_inline_test


See link:https://github.com/janestreet/ppx_inline_test[ppx_inline_test,window="_blank"]

For ppx_inline_test we need to use the ppx_executable to transform the
source file, and we need to run `Ppx_inline_test_lib.Runtime.exit ()`
last. The demos put the latter in `runner.ml` and link it last by
passing it to the `main` attribute of `ocaml_test`.

NOTE: that's what  "@ppx_inline_test//lib/runner" does, use it instead.

Tests are only executed when both these conditions are met:

* Code using this extension must be compiled and linked using the
  `ppx_inline_test.runtime-lib` library.
  (`@ppx_inline_test//lib/runtime-lib`)

* the module under test is compiled with `-inline-test-lib <libname>`.
** This tags the ppx inline tests  in the module with `<libname>`.

* the executable linked with the modules under test is linked with
  `ppx_inline_test.runner.lib` (see `runtime lib` below for more on this)

    ppx_link_codeps = ["@ppx_inline_test//lib/runner/lib"]


* the executable (e.g. `your.exe`) linked with the modules under test
is called with command line arguments: 'your.exe inline-test-runner
<libname> [options]'
** The tag `<libname>` is what selects tests to be executed: any
   inline test tagged by <libname> will be executed; tests not so
   tagged will be ignored.


"Finally, after running tests,`Ppx_inline_test_lib.Runtime.exit ()`
should be called (to exit with an error and a summary of the number of
failed tests if there were errors or exit normally otherwise)."

The lib provides this precompiled: `@ppx_inline_test//lib/runner`


WARNING: If you pass the wrong <libname> on the command line (as arg
to `inline-test-runner`), then the intended tests will _not_ be
executed. The test run may succeed, but that does not mean that your
tests have passed.

This tagging mechanism allows you to link modules compiled with
different ppx_inline_test tags ("libnames"), and select which tests to
execute at runtime. See demo `testing/ppx_inline_test/compound` for an
example.

== runtime lib

ppx_inline_test.runner.lib


== examples

from dune logs:

```
$ (cd _build/default/compiler/tests-jsoo && .jsoo_testsuite.inline-tests/inline_test_runner_jsoo_testsuite.exe inline-test-runner jsoo_testsuite -source-tree-root ../.. -diff-cmd - -allow-output-patterns)
```


$ (cd _build/default/compiler/tests-compiler && .jsooexp_build_path_prefix_map.inline-tests/inline_test_runner_jsooexp_build_path_prefix_map.exe inline-test-runner jsooexp_build_path_prefix_map -source-tree-root ../.. -diff-cmd - -allow-output-patterns)


