= makefiles

These examples demonstrate the OCaml build discipline using makefiles.

The Makefile demos depend on an link:https://opam.ocaml.org/[OPAM]
installation with the following packages installed:

* ocamlfind (findlib)
* ounit2

To start from scratch, install OPAM and then:

```
$ opam update
$ opam switch create <version>           <1>
$ eval $(opam env)
$ opam install ocamlfind ounit2
```
<1> Where <version> = 4.14.0, 5.1.1, etc.

You can tell OPAM to list the packages installed in the current
switch: `$ opam  list`.

Run `make` from the top directory or any of the subdirectories. Some
of the targets are expected to fail, as illustration of some aspect of
OCaml builds. Most demos are documented in the Makefiles and/or README
files.

WARNING: In some cases warnings or errors will only occur the first
time you run make. The "Expected output" messages will always print,
but if you rerun make, you won't see the expected output. Examine the
Makefile to see why. To see all messages, run `make clean` before
rerunning `make`. All Makefiles include a `make clean` target.
